### ISSUE TITLE
Parameter #1 (zone name) missed line 1301 on respawn

### ISSUE THREAD

**Issue by thebgpikester** [birgersp/dcs-autogft#99] opened 2017-02-16 13:28 UTC
When attempting to respawn the scripting engine throws an error Parameter #1 (zone name) missed. The error is present in the 1.8 demo included, just wind on speed until a respawn is called on a dead group.

**Comment by birgersp** [comment] 2017-02-16 14:18
Will investigate this in a couple of hours, thanks for reporting

**Comment by thebgpikester** [comment] 2017-02-20 10:16
As mentioned in IM, pretty sure this is a conflict when running an older MIST on top of the current one embedded.

**Comment by birgersp** [comment] 2017-02-24 13:50
Appeared to be caused by using multiple copies of mist in a single mission. Should be fixed with #50, closing

**Closed by birgersp** 2017-02-24 13:50 UTC
Labels: bug
